[workspace]
resolver = "2"
members = ["bot-gateway", "./vendor/randy-*"]

#[workspace.package]
#name = "randy"
#description = "randombot's second coming"
#authors = ["swrge", "Twilight Contributors"]
#edition = '2021'
#rust-version = "1.84.0"
#license = "ISC"
