[package]
authors.workspace = true
categories = ["api-bindings"]
description = "Functions and constants for validating request parameters"
edition.workspace = true
homepage = "https://twilight.rs/"
include.workspace = true
keywords = ["discord", "discord-api", "twilight"]
license.workspace = true
name = "randy-validate"
publish = true
repository = "https://github.com/swrge/randy-validate"
rust-version.workspace = true
version = "0.1.0"

[dependencies]
twilight-model = { default-features = false, git = "https://github.com/swrge/randy-model", version = "0.1.0" }

[dev-dependencies]
static_assertions = { default-features = false, version = "1.1.0" }
