steps:
  - id: "Build and Push Container Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$_GCR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA",
        ".",
      ]
  - id: "Push Container Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$_GCR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA",
      ]
  - id: "Deploy to Cloud Run"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}-$BUILD_ID"
      - "--image"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - "--region"
      - "${_DEPLOY_REGION}"
      - "--set-env-vars"
      - "DISCORD_BOT_TOKEN=$$BOT_TOKEN"
      - "--startup-probe"
      - "httpGet.path=/probe,httpGet.port=8080,initialDelaySeconds=60,failureThreshold=20,timeoutSeconds=30,periodSeconds=10"
      - "--allow-unauthenticated"
    secretEnv: ["BOT_TOKEN"]

availableSecrets:
  secretManager:
    - versionName: projects/750978330037/secrets/BOT_TOKEN/versions/latest
      env: BOT_TOKEN
