steps:
  - id: "Build and Push Container Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$_GCR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA",
        ".",
      ]
  - id: "Push Container Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$_GCR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA",
      ]
  - id: "Deploy to Cloud Run"
    name: "gcr.io/cloud-builders/gcloud"
    args: [
        "run deploy bot-requester
        --image $_GCR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest
        --region us-east1
        --set-env-vars DISCORD_BOT_TOKEN=$$BOT_TOKEN
        --allow-unauthenticated
        ",
      ]
    secretEnv: ["BOT_TOKEN"]
    timeout: 3600s
availableSecrets:
  secretManager:
    - versionName: projects/750978330037/secrets/BOT_TOKEN/versions/latest
      env: BOT_TOKEN
