name = "bot-worker"
main = "src/index.ts"
compatibility_date = "2023-10-16"
compatibility_flags = ["nodejs_compat"]

[env.production]
workers_dev = false

[env.development]
workers_dev = true

[vars]
PUBLIC_KEY = "3623ce7e20f325f139721246d3291b6d957ecfd18949742eff378179b18a6bbe"
APPLICATION_ID = "1068127668052168704"

# Note: For secrets like BOT_TOKEN, use the Wrangler CLI:
# Public variables can be defined here
# wrangler secret put BOT_TOKEN
